### ISSUE TITLE
Primary File Structure

### ISSUE THREAD

**Issue by scott-wyatt** [CaliStyle/generator-treefrog#1]
##Concept
In sails apps and some trails apps, a folder named `assets` and `views` are traditional.  However, since we are expecting to make isomorphic applications, I believe a single folder named `app` is more acceptable. This will make it a single separation of concern from the `api`.

**Comment by jaumard** [comment]
Sound good to have one folder.
Does this mean that `app` will have all all the `api` folder of Trails ? 

```
root 
--api
--app

OR
root
--app
----api
```

**Comment by scott-wyatt** [comment]
It would be:
```
root
--api
--app
```

**Comment by scott-wyatt** [comment]
Technically speaking, it might be a good idea to have a `src` folder that then compiles into an `app` folder.

**Comment by jaumard** [comment]
```
root
--api
--app
```
Ok :) sound more easy to set up this way ^^. 

> Technically speaking, it might be a good idea to have a src folder that then compiles into an app folder.

Hum if you put the app folder as `www` directory for static resources yes... But personally I don't mind have only an app (or src) folder the compiles directly into the `www` folder. 

Because if first you have `src` compile into `app` and then `app` move into `www` it's a lot of manipulation for nothing ^^

**Comment by scott-wyatt** [comment]
> Because if first you have src compile into app and then app move into www it's a lot of manipulation for nothing ^^
Good point!  Okay, we will do an `app` folder that compiles into `www`.

**Comment by scott-wyatt** [comment]
This <https://github.com/aclave1/trailpack-client> Is using some similar methodology.

**Comment by scott-wyatt** [comment]
So we will need to add another step to determine source and destination for compiling.  This would mean that `app` and `dist` will not be defacto.  I'll close this issue and open another.
