### ISSUE TITLE
Webpack or Gulp or Grunt or User Choice?

### ISSUE THREAD

**Issue by scott-wyatt** [CaliStyle/generator-treefrog#3]
So, I don't want to make anything to opinionated, but should we enforce some sort of task manager? My preference is webpack for this I'd imagine.

**Comment by jaumard** [comment]
What about giving the choice when the project is generated ? I can do the config for `trailpack-gulp` as I know it. If you know webpack we can have both and let the user use the one it prefer

**Comment by scott-wyatt** [comment]
@jaumard Good idea!

**Comment by scott-wyatt** [comment]
So during setup we've realized that using webpack for backend of Trails apps is extremely difficult to do.  Right now, we plan to support Gulp for the start.

**Comment by scott-wyatt** [comment]
I'm closing this issue sense it is decided that we will support all 3 task managers and start with supporting gulp.
